name: Deploy to DigitalOcean Droplet

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            cd /var/www/ceylontransit-api || git clone https://github.com/IshanKM/CeylonTransit-API.git /var/www/ceylontransit-api
            cd /var/www/ceylontransit-api
            git fetch --all
            git reset --hard origin/main
            npm ci
            pm2 reload ecosystem.config.js --env production || pm2 start ecosystem.config.js --env production
            pm2 save

